name: Cache CI

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dummy dependency folder
        run: |
          mkdir -p dependencies
          echo "dependency-file" > dependencies/file.txt

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: dependencies
          key: cache-3a5718a

      - name: prime-cache-3a5718a
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"